version: '3.8'

services:
  # Основное приложение (новая архитектура)
  app-new:
    build:
      context: .
      dockerfile: Dockerfile.new
      target: development
    ports:
      - "8001:8000"  # Другой порт, чтобы не конфликтовать со старым
    environment:
      - BOT_TOKEN=${BOT_TOKEN:-7105955108:AAHf4cICJWShQfoixAfvVBt_5a3KleCJw_Q}
      - DOMAIN=${DOMAIN:-http://localhost:8001}
      - VERIFY_TELEGRAM_SIGNATURE=false
      - DATABASE_URL=postgresql://postgres:password@db:5432/telegram_app
      - TESTING=false
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    command: python main_refactored.py

  # Старое приложение (для совместимости)
  app-old:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN:-7105955108:AAHf4cICJWShQfoixAfvVBt_5a3KleCJw_Q}
      - DOMAIN=${DOMAIN:-http://localhost:8000}
      - VERIFY_TELEGRAM_SIGNATURE=false
      - DATABASE_URL=postgresql://postgres:password@db:5432/telegram_app
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    command: python start_server.py

  # Сервис для тестирования
  test:
    build:
      context: .
      dockerfile: Dockerfile.new
      target: testing
    environment:
      - TESTING=true
      - DATABASE_URL=postgresql://postgres:password@test-db:5432/test_db
    volumes:
      - .:/app
      - ./htmlcov:/app/htmlcov  # Для отчетов покрытия
    depends_on:
      - test-db
    profiles:
      - testing

  # База данных для основного приложения
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=telegram_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  # База данных для тестов
  test-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    profiles:
      - testing

  # Adminer для управления БД
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  # Redis для кеширования (опционально)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - cache

volumes:
  postgres_data:
  test_postgres_data:
  redis_data: