name: Build and Deploy

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  deploy:
    name: Upload bot to Netangels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "."
          target: "/home/${{ secrets.SSH_USERNAME }}/dialist.ru/app"
          rm: true
          strip_components: 0

      - name: Apply DB migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export DATABASE_URL='${{ secrets.DATABASE_URL }}'
            python3 /home/${{ secrets.SSH_USERNAME }}/dialist.ru/app/migrations/apply_migrations.py

      - name: Touch restart trigger
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            touch /home/${{ secrets.SSH_USERNAME }}/dialist.ru/reload
