name: Build and Deploy

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  build-and-deploy:
    name: Build frontend and deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install NPM dependencies
        run: npm ci

      - name: Build frontend
        run: npm run prod

      - name: Deploy to server via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./"
          target: "/home/${{ secrets.SSH_USERNAME }}/rptx.na4u.ru/app"
          rm: false
          strip_components: 0

#        - name: Run database migrations
#          if: github.ref == 'refs/heads/main'
#          uses: appleboy/ssh-action@master
#          with:
#            host: ${{ secrets.SSH_HOST }}
#            username: ${{ secrets.SSH_USERNAME }}
#            password: ${{ secrets.SSH_PASSWORD }}
#            script: |
#              cd /home/${{ secrets.SSH_USERNAME }}/speka.dev/app
#              php artisan migrate --force
